modules:
  - androidApp
  - desktopApp
  - iosApp
  - plugins/secrets
  - plugins/sqldelight
  - plugins/webdist
  - shared
  - webApp

plugins:
  - ./plugins/secrets
  - ./plugins/sqldelight
  - ./plugins/webdist
